### ISSUE TITLE
Application.js

### ISSUE THREAD

**Issue by thinkblue721** [corielynch/fuel-database#6]
Application.js: 
![applicationjs.PNG](https://images.zenhubusercontent.com/5eb0c3702f6c2059e533c36a/d87

Could instantiate Express here again, or we could pass in “app” into this file
Router is a part of Express; all we’re doing is using the routing aspect of it now for speed instead of using the entire Express instance
In line 4, we are going to our controller. This is where we handle our actual routing. Before we were just modularizing our routes, but now we are doing our routing; routes are going to tell us which controller to go to based on the route that we are at.
So in line 6, it tells us that we are now on everything that matches anything at the root ‘/’ location, any http method for the root location (GET, POST, PUT, DELETE, etc). For this particular one, we only have GET. The second argument, “application_controller”, is the controller file. The .index refers to a specific method inside “application_controller” called “index”. So the second argument is a function call, a callback function. Another example of modularizing vs having the cb function directly in there.
This is the first part of our MVC model. router.get(‘/’, is the routing, and application_controller.index); is the logic:
![application controller.PNG](https://images.zenhubusercontent.com/5eb0c3702f6c2059e533c36a/29f08ac2-9c7e-49e1-bd4c-42d7988f004d)81883-76be-49af-b143-a8598287eff5)

**Comment by Kathleen-Y** [comment]
we are using User.js in place of Application.js for our project
