### ISSUE TITLE
Application_controller.js

### ISSUE THREAD

**Issue by thinkblue721** [corielynch/fuel-database#7]
Index is a method off of the Exports object that we are exporting. What we’re exporting and what it is is simply a function that renders the “index.handlebars” file. So since we imported/required it in the application.js file using the const application_controller, we can call it in that file using application_controller.index
So controllers control what you’re going to do next, logic controllers
Client gives info i.e. GET, POST, etc., and the controller determines what to do with it next. In this case, it’s rendering the “index” page
Since it’s only a GET request, we don’t need “req” as a parameter
All the other routes include a controller as well. In each controller is another function, i.e., pricing_controller.index renders a file called “pricing.handlebars” file within the Pricing folder within Views, done with res.render(‘pricing/pricing’);
Since we’re rendering from the Views directory, the application_controller just needs to render “index” within the Views directory. But for pricing_controller, the file we need is within the Pricing directory inside Views and called Pricing, so we refer to it this way

**Comment by Kathleen-Y** [comment]
Using user_controller.js in place of application_controller.js
